### PR TITLE
Feat/use tahu for sparkplug decoding

### PR DESCRIPTION
**Pull request by bj00rn**
Use tahu https://github.com/eclipse/tahu for sparkplug

Based on #793 

## Changes
- [x] use `sparkplug-payload` for decoding
- [x] add sparkplugb client script using `sparkplug-client` #781 
- [x] add sparkplugb messages to demo video

@thomasnordquist thoughts on this?, Why roll our own decoding, but maybe you have been down this road before?

### CODE REVIEW

**Comment by thomasnordquist** [comment]
I'll try to merge this work with https://github.com/thomasnordquist/MQTT-Explorer/pull/493, and move the decoding in the fronted.
This would allow the user to select the decoding method, a default should be selected based on the topic path or the first bytes of the data.

**Comment by thomasnordquist** [comment]
This should make it much easier to decode different data types in the future.

**Comment by bj00rn** [comment]
> I'll try to merge this work with #493, and move the decoding in the fronted. This would allow the user to select the decoding method, a default should be selected based on the topic path or the first bytes of the data.

Sounds good. An "Auto detect" mode for decoding with the possibility for manual override would be awesome. Checkout file-type https://www.npmjs.com/package/file-type package, it has detection of binary payloads. A possibility to download binary payloads would be awesome too!

**Comment by bj00rn** [comment]
@thomasnordquist pushed commits with sparkplug client for demoVideo

**Pull request merged**
