### PR TITLE
Added support for binary data types

### PR DESCRIPTION
**Pull request by mhorsche**
image
# New Features
- Select data type (string, json, hex, uint, int, float) for each topic individually
- Default data type is 'string'
- Binary types are decoded with 'little Endian' ('readUInt__LE', 'readInt__LE, 'readFloatLE' and 'readDoubleLE')
- Show milliseconds in message received timestamp (feature request #479)

# Todo
Minor issue when changing data type you need to reselect the topic to fire render event. This should be done automatically, maybe you can help me to implement this properly.

### CODE REVIEW

**Comment by stefanlk** [comment]
is it possible to finalize the merge?

**Comment by mhorsche** [comment]
> is it possible to finalize the merge?

Never got any reaction from @thomasnordquist. I use this functionality very often, should be implemented correctly...

**Comment by ilgrank** [comment]
The author is not visiting Github anymore (last time he replied was end of 2022), and that's a shame :(

**Comment by Redsandro** [comment]
I just discovered this tool, which is very nice, and came here just to suggest the same feature.

image

Unfortunately this tool is no longer maintained. I had no idea it was 3 years old. Now I need to find something else. :sweat_smile:  What did you end up using? Found anything similar that supports binary?

**Comment by bj00rn** [comment]
@mhorsche can you rebase this PR and i'll try to get it merged?

Ideally the timestamp coudl be a separate PR.

**Pull request merged**
